### ISSUE TITLE
Game UI bugs out when there are more than 4 players

### ISSUE THREAD

**Issue by ashiqurrah7** [OldManAlpha/Monopoly-Deal#5]
![image](https://user-images.githubusercontent.com/8469875/231303476-db2e69e9-b282-41a8-8963-0eb3dea9aa3a.png)
You can't see the fifth player

**Comment by OldManAlpha** [comment]
The game currently does not support more than 4 players in its UI. The next update will allow for unlimited players.

**Comment by OldManAlpha** [comment]
Fixed in b1e043be8260a8e088ee52f0da759f6424e28d3c. Changes will be present in next release.
