### ISSUE TITLE
Multicolored rent card charges all players, discarding extra cards

### ISSUE THREAD

**Issue by guocuozuoduo** [OldManAlpha/Monopoly-Deal#6]
The multicolored rent card charges all players, but it should charge only one player.
![image](https://github.com/OldManAlpha/Monopoly-Deal/assets/32423716/cffe3cc0-43c5-4f3b-9f04-1e1251ce6eca)
From the [official rules](https://web.archive.org/web/20090407120541/http://host.exemplum.com/hasbro/hasbro-card-games/pdf/monopolyDeal.pdf):
>  **Multi-colored Rent card**: 
Charge **one player of your 
choice** rent on any of your 
properties. 

In addition:
> If you have more than 7 cards in your hand at the end of your turn (not including 
cards on the table) discard extras **to the bottom of the draw pile** so you only have 7.

However, in this program, extras are discarded directly to the top of the discard pile.

**Comment by OldManAlpha** [comment]
There are many small details in the default game rules that technically don't follow the official rules, including multi-color rent charging all players. This rule, and many others, can be changed using the `/rules` command.

That said, I completely missed that the official rules states discarded cards should go to the bottom of the deck. That will be added as another game rule in the next update.

**Comment by OldManAlpha** [comment]
Implemented a game rule to be able to change where discarded cards go in 6e394bdbe534d249f706605db58db40a5f83306c under "Discard Rules." This will be present in the next release.
