### ISSUE TITLE
Empty hand draws 5 at start or end?

### ISSUE THREAD

**Issue by guocuozuoduo** [OldManAlpha/Monopoly-Deal#7]
The official rules (linked in a previous issue) state:
>If you’ve run out of cards, take 5 **at the start of your next turn**.

But the program draws the 5 cards at the end of the turn, and when the turn comes again, 2 more are drawn. From how I understand, the player who had no cards at the end should now have 5 cards, and not 7 (from 5 at the end + 2 at the start).

I am not sure if this is the program's bug or just another house rule.

**Comment by OldManAlpha** [comment]
This is indeed another rule that I've intentionally deviated from. This behavior is also a game rule that can be modified with the `/rules` command, found inside `Empty Hand Rules`.
